# -*- coding: utf-8 -*-
"""TIC TAC TOE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17cSvX4NtT9jiShzUNJ6_ic2l6Pqpaf9U
"""

# Tic Tac Toe Game in Python

# Function to print the Tic Tac Toe board
def print_board(board):
    print("\n")
    for row in board:
        print(" | ".join(row))
        print("-" * 5)
    print("\n")

# Function to check for a win
def check_win(board, player):
    # Check rows, columns, and diagonals
    for i in range(3):
        if all([cell == player for cell in board[i]]) or all([board[j][i] == player for j in range(3)]):
            return True
    if board[0][0] == board[1][1] == board[2][2] == player or board[0][2] == board[1][1] == board[2][0] == player:
        return True
    return False

# Function to check for a draw
def check_draw(board):
    return all([cell in ["X", "O"] for row in board for cell in row])

# Function to make a move
def make_move(board, player):
    while True:
        move = input(f"Player {player}, enter your move (row and column number from 1-3, separated by a space): ").split()
        if len(move) != 2 or not all(m.isdigit() and 1 <= int(m) <= 3 for m in move):
            print("Invalid input! Please enter two numbers between 1 and 3.")
            continue
        row, col = int(move[0]) - 1, int(move[1]) - 1
        if board[row][col] == " ":
            board[row][col] = player
            break
        else:
            print("That position is already taken. Try again.")

# Function to start the Tic Tac Toe game
def start_game():
    board = [[" " for _ in range(3)] for _ in range(3)]
    current_player = "X"

    while True:
        print_board(board)
        make_move(board, current_player)

        if check_win(board, current_player):
            print_board(board)
            print(f"Player {current_player} wins!")
            break
        elif check_draw(board):
            print_board(board)
            print("It's a draw!")
            break

        current_player = "O" if current_player == "X" else "X"

# Start the game
start_game()